flt1 = +1
flt2 = 3.1415
flt3 = 5e+22
flt4 = 1e06
flt5 = -2E-2
sf1 = -inf
sf2 = +nan 

[datas]
lt1 = 1998-06-24T03:22:00
lt2 = 1979-05-27T00:32:00.999999

contributors = [
  "Foo Bar <foo@example.com>",
  { name = "Baz Qux", email = "bazqux@example.com", url = "https://example.com/bazqux" }
]

[dog."tater.man"]
type.name = "pug"

[fruit]
apple.color = "red"
apple.taste.sweet = true

[product]
type = { name = "Nail" }

[[products]]
name = "Hammer"
sku = 738594937

[[fruits.varieties]]
name = "granny smith"