tittle = "TOML EXAMPLE"

[person]
name.proprio = "John"
name.secundario = "Doe"
age.birth = 30

[animal]
type = "raposa"
pet_name = "coccy"
pet_age = 12

[animal.pet]
type = "dog"
pet_name = "Puffy"
pet_age = 3

[address.road.California]
street = "123 Main St"
city = "Anytown"
state = "CA"
zip = 12345
mylist = [0,false,"falso"]
pessoa = { nome = "Nail", idade = 24 }
final = true
