[[fruits]]
name = "apple"

# subtable
[fruits.physical]  
color = "red"
shape = "round"

# nested array of tables
[[fruits.varieties]]  
name = "red delicious"

[[fruits.varieties]]
name = "granny smith"

[[fruits]]
name = "banana"


[[fruits.varieties]]
name = "plantain"