[[fruits]]
name = "apple"

# subtable
[fruits.physical]  
color = "red"
shape = "round"

# nested array of tables
[[fruits.varieties.summer]]  
name = "red delicious"

[[fruits.varieties.summer]]
name = "granny smith"


[[fruits]]
name = "banana"

[[fruits.varieties]]
name = "plantain"
