[[fruits]]
name = "apple"

# subtable
[fruits.physical]  
color = "red"
shape = "round"

# nested array of tables
[[fruits.spring]]  
name = "red delicious"

[[fruits.varieties.summer]]
name = "granny smith"


[[fruits]]
name = "banana"

[[fruits.varieties]]
name = "plantain"


[[fruits]]
name = "morangos"

[[fruits.color]]
color = "red"
country = "portugal"
continente = "europa"

[[market]]
name = "continente"

[[market.fruits]]
name = "amanhecer"
