tittle = "TOML EXAMPLE"

[person]
name.proprio = "John"
name.apelido = "Doe"
age.birth = 30

[animal]
type = "raposa"
pet_name = "coccy"
pet_age = 8

[animal.pet]
type = "dog"
pet_name = "Puffy"
pet_age = 3

[address.road.California]
street = "123 Main St"
city = "Anytown"
state = "CA"
zip = 12345
habitantes = [{ nome = "Alex", idade = 24 }]