flt1 = +1
flt2 = 3.1415
flt3 = 5e+22
flt4 = 1e06
flt5 = -2E-2
sf1 = -inf
sf2 = +nan
odt1 = 1979-05-27T07:32:00Z
odt2 = 1979-05-27T00:32:00-07:00
odt3 = 1979-05-27T00:32:00.999999-07:00

contributors = ["Foo Bar <foo@example.com>",{ name = "Baz Qux", email = "bazqux@example.com", url = "https://example.com/bazqux" }]

[datas]
lt1 = 1998-06-24T03:22:00
lt2 = 1979-05-27T00:32:00.999999


[dog."tater.man"]
type.name = "pug"

[fruit]
apple.color = "red"
apple.taste.sweet = true

[product]
type = { name = "Nail" }

[[products]]
name = "Hammer"
sku = 738594937

[[fruits.varieties]]
name = "granny smith"
